#!/usr/bin/env node
/**
 * make_theme.mjs — lock a project's look.
 *
 * Given a chosen Sanzo Wada combination and a target (preprint/journal/grant),
 * write theme.json + theme.css to the project. House neutrals/ink/paper/tints stay
 * constant; the combo sets primary + accents; fonts are resolved to what the target permits.
 *
 * Fonts have NO default — the user must choose them (via the font chooser). Pass the chosen fonts
 * with --figures / --display / --body. If a chosen font isn't permitted for the target, the nearest
 * permitted substitute is used and flagged.
 *
 * Usage:
 *   node make_theme.mjs --combo <id> --target <target> --figures <font> --display <font> --body <font> [--name <p>] [--out <dir>]
 * Example:
 *   node make_theme.mjs --combo house-coral-greige --target preprint \
 *     --figures "Space Grotesk" --display "Space Grotesk" --body "Public Sans" --name lion --out ./figures
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const ASSETS = resolve(__dir, "../assets");

function arg(flag, def = null) {
  const i = process.argv.indexOf(flag);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

const comboId = arg("--combo", "house-coral-greige");
const target = arg("--target", "preprint");
const name = arg("--name", comboId);
const outDir = resolve(arg("--out", "."));

const sanzo = JSON.parse(readFileSync(join(ASSETS, "sanzo-wada.json"), "utf8"));
const fonts = JSON.parse(readFileSync(join(ASSETS, "journal-fonts.json"), "utf8"));

const combo = sanzo.combinations.find((c) => c.id === comboId);
if (!combo) {
  console.error(`Unknown combo "${comboId}". Available: ${sanzo.combinations.map((c) => c.id).join(", ")}`);
  process.exit(1);
}
const tgt = fonts.targets[target];
if (!tgt) {
  console.error(`Unknown target "${target}". Available: ${Object.keys(fonts.targets).join(", ")}`);
  process.exit(1);
}

// House constants (never change with the combo) — see house-style.md.
const HOUSE = {
  neutralRamp: ["#6B5B4F", "#8A7E74", "#A49890"],
  ink: "#3D342E", inkMuted: "#5A4D43", inkFaint: "#8A8078",
  hairline: "#E0E0E0", paper: "#FFFFFF",
  tints: ["#FFF5EF", "#F9F5F0", "#F5F3F1", "#F3F0ED"],
  spacing: [4, 8, 16, 24, 40, 64],
};

// Combo -> primary + accents. First color = primary; the rest become accents (drop near-ink darks).
const cols = combo.colors;
const primary = cols[0];
const accents = cols.slice(1).filter((c) => c.toLowerCase() !== HOUSE.ink.toLowerCase());

// Fonts: NO default — the user chooses. Read the chosen fonts from args; error if missing.
const chosen = { figures: arg("--figures"), display: arg("--display"), body: arg("--body") };
if (!chosen.figures || !chosen.display || !chosen.body) {
  console.error("No default font. Run the font chooser, then pass the chosen fonts:");
  console.error('  --figures "<font>" --display "<font>" --body "<font>"');
  console.error(`Permitted for "${target}": ${tgt.allowed.join(", ")}`);
  process.exit(1);
}
const flags = [];
function resolveFont(role, want) {
  if (tgt.allowed.includes(want)) return want;
  const sub = fonts.meta.substitutes[want] || tgt.allowed[0];
  flags.push(`${role}: "${want}" not permitted for ${target} → substituted "${sub}"`);
  return sub;
}
const resolvedFonts = {
  figures: resolveFont("figures", chosen.figures),
  display: resolveFont("display", chosen.display),
  body: resolveFont("body", chosen.body),
};

const theme = {
  name,
  source: `Sanzo Wada — A Dictionary of Color Combinations (${combo.name}, ${comboId})`,
  palette: {
    primary,
    primaryRamp: [primary],
    neutral: HOUSE.neutralRamp[1],
    neutralRamp: HOUSE.neutralRamp,
    accents,
    ink: HOUSE.ink, inkMuted: HOUSE.inkMuted, inkFaint: HOUSE.inkFaint,
    hairline: HOUSE.hairline, paper: HOUSE.paper, tints: HOUSE.tints,
  },
  target,
  fonts: resolvedFonts,
  fontFlags: flags,
  spacing: HOUSE.spacing,
  export: {
    format: ["svg", "pdf"],
    dpi: tgt.sizing.dpi || 300,
    widthIn: { single: tgt.sizing.single, double: tgt.sizing.double },
    minPt: tgt.sizing.minPt,
  },
};

// Emit theme.css — CSS custom properties every harness @imports.
const accentVars = accents.map((c, i) => `  --accent-${i + 1}: ${c};`).join("\n");
const tintVars = HOUSE.tints.map((c, i) => `  --tint-${i + 1}: ${c};`).join("\n");
// Web-font @imports for the chosen fonts (system fonts have no entry and need none).
const wf = fonts.meta.webfonts || {};
const importUrls = [...new Set(Object.values(resolvedFonts))].map((f) => wf[f]).filter(Boolean);
const imports = importUrls.map((u) => `@import url('${u}');`).join("\n");
const SYS = "system-ui, -apple-system, Segoe UI, Roboto, sans-serif";
const css = `/* theme.css — generated by ATELIER make_theme.mjs. Do not hand-edit; re-run instead. */
${imports}${imports ? "\n" : ""}:root {
  --primary: ${primary};
  --neutral: ${HOUSE.neutralRamp[1]};
  --neutral-dark: ${HOUSE.neutralRamp[0]};
  --neutral-light: ${HOUSE.neutralRamp[2]};
${accentVars}
  --ink: ${HOUSE.ink};
  --ink-muted: ${HOUSE.inkMuted};
  --ink-faint: ${HOUSE.inkFaint};
  --hairline: ${HOUSE.hairline};
  --paper: ${HOUSE.paper};
${tintVars}
  --font-figures: "${resolvedFonts.figures}", ${SYS};
  --font-display: "${resolvedFonts.display}", ${SYS};
  --font-body: "${resolvedFonts.body}", ${SYS};
  --space-1: 4px; --space-2: 8px; --space-3: 16px; --space-4: 24px; --space-5: 40px; --space-6: 64px;
}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "theme.json"), JSON.stringify(theme, null, 2) + "\n");
writeFileSync(join(outDir, "theme.css"), css);

console.log(`✓ Locked theme "${name}" → ${join(outDir, "theme.json")} + theme.css`);
console.log(`  combo: ${combo.name}  ·  target: ${tgt.label}`);
console.log(`  primary ${primary}  accents ${accents.join(" ") || "(none)"}`);
console.log(`  fonts: figures=${resolvedFonts.figures} display=${resolvedFonts.display} body=${resolvedFonts.body}`);
if (flags.length) flags.forEach((f) => console.log(`  ⚠ ${f}`));
